version: '3.5'

services:
  web:
    container_name: odin-api
    build:
      context: .
      dockerfile: python/Dockerfile
    # command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 254"
    ports:
    - 3010:254
    volumes:
    - ./app:/app